### ISSUE TITLE
TypeError: undefined is not iterable

### ISSUE THREAD

**Issue by ziodave** [googledatastudio/tooling#347]
Just installed, running
```
npx @google/dscc-gen connector --script_id "(redacted)"                                                                                                                         

./node_modules/macos-release/index.js:27
        const [name, version] = nameMap.get(release);

                                ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (node_modules/macos-release/index.js:27:26)
    at osName (node_modules/os-name/index.js:21:18)
    at new Insight (node_modules/insight/lib/index.js:37:13)
    at Object.<anonymous> (node_modules/@google/dscc-gen/build/analytics.js:13:17)
```

It's an existing project. Node v16.17.0, dev deps:

```
"devDependencies": {
    "@google/dscc-gen": "^2.0.31",
    "@types/google-apps-script": "^1.0.49",
    "@types/jasmine": "^4.0.3",
    "@types/jsonpath": "^0.2.0",
    "husky": "^8.0.2",
    "jasmine": "^4.0.2",
    "path": "^0.12.7",
    "prettier": "^2.8.0",
    "pretty-quick": "^3.1.3",
    "ts-node": "^10.8.2",
    "typescript": "^4.7.4"
  }
```

**Comment by dnsdrs** [comment]
we need "insight": "^0.11.1" for it to work on newer MacOS versions
